# Data Understanding

In [5]:

from src.data_loader import load_all_csv

In [8]:
data = load_all_csv()
data.keys()

dict_keys(['calendar.csv', 'data_dictionary.csv', 'inventory.csv', 'products.csv', 'sales.csv', 'stores.csv'])

### Calendar

In [12]:
calendar_df = data['calendar.csv']
calendar_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 638 entries, 0 to 637
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    638 non-null    str
dtypes: str(1)
memory usage: 5.1 KB

In [15]:
display(calendar_df.head())
display(calendar_df.tail())

       Date
0  1/1/2022
1  1/2/2022
2  1/3/2022
3  1/4/2022
4  1/5/2022

          Date
633  9/26/2023
634  9/27/2023
635  9/28/2023
636  9/29/2023
637  9/30/2023

### Data Dictionary

In [20]:
calendar_df = data['data_dictionary.csv']
calendar_df.head(10)

,Table,Field,Description
0,Products,Product_ID,Product ID
1,Products,Product_Name,Product name
2,Products,Product_Category,Product Category
3,Products,Product_Cost,Product cost ($USD)
4,Products,Product_Price,Product retail price ($USD)
5,Inventory,Store_ID,Store ID
6,Inventory,Product_ID,Product ID
7,Inventory,Stock_On_Hand,Stock quantity of the product in the store (in...
8,Stores,Store_ID,Store ID
9,Stores,Store_Name,Store name

In [18]:
calendar_df.describe()

           Table       Field Description
count         19          19          19
unique         5          14          15
top     Products  Product_ID  Product ID
freq           5           3           3

In [19]:
calendar_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Table        19 non-null     str
 1   Field        19 non-null     str
 2   Description  19 non-null     str
dtypes: str(3)
memory usage: 588.0 bytes