# Data Understanding

In [29]:
import sys
from pathlib import Path

# Add the project root to Python path
project_root = Path().resolve().parent
sys.path.insert(0, str(project_root.parent))

# Import the data loader function that will load all CSV files
from src.data_loader import load_all_csv

In [33]:
data = load_all_csv()
data.keys()

dict_keys(['calendar.csv', 'data_dictionary.csv', 'inventory.csv', 'products.csv', 'sales.csv', 'stores.csv'])

### Calendar

In [6]:
calendar_df = data['calendar.csv']
calendar_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 638 entries, 0 to 637
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    638 non-null    str
dtypes: str(1)
memory usage: 5.1 KB

In [7]:
display(calendar_df.head())
display(calendar_df.tail())

       Date
0  1/1/2022
1  1/2/2022
2  1/3/2022
3  1/4/2022
4  1/5/2022

          Date
633  9/26/2023
634  9/27/2023
635  9/28/2023
636  9/29/2023
637  9/30/2023

### Data Dictionary

In [47]:
calendar_df = data['data_dictionary.csv']
calendar_df.head(10)

,Table,Field,Description
0,Products,Product_ID,Product ID
1,Products,Product_Name,Product name
2,Products,Product_Category,Product Category
3,Products,Product_Cost,Product cost ($USD)
4,Products,Product_Price,Product retail price ($USD)
5,Inventory,Store_ID,Store ID
6,Inventory,Product_ID,Product ID
7,Inventory,Stock_On_Hand,Stock quantity of the product in the store (in...
8,Stores,Store_ID,Store ID
9,Stores,Store_Name,Store name

In [9]:
calendar_df.describe()

           Table       Field Description
count         19          19          19
unique         5          14          15
top     Products  Product_ID  Product ID
freq           5           3           3

In [10]:
calendar_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Table        19 non-null     str
 1   Field        19 non-null     str
 2   Description  19 non-null     str
dtypes: str(3)
memory usage: 588.0 bytes

### Inventory

In [11]:
inventory_df = data['inventory.csv']
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1593 entries, 0 to 1592
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Store_ID       1593 non-null   int64
 1   Product_ID     1593 non-null   int64
 2   Stock_On_Hand  1593 non-null   int64
dtypes: int64(3)
memory usage: 37.5 KB

In [12]:
inventory_df.head()

   Store_ID  Product_ID  Stock_On_Hand
0         1           1             27
1         1           2              0
2         1           3             32
3         1           4              6
4         1           5              0

In [14]:
inventory_df.describe()

          Store_ID   Product_ID  Stock_On_Hand
count  1593.000000  1593.000000    1593.000000
mean     25.326428    18.073446      18.670433
std      14.477592    10.064254      18.997652
min       1.000000     1.000000       0.000000
25%      13.000000     9.000000       6.000000
50%      25.000000    18.000000      13.000000
75%      38.000000    27.000000      24.000000
max      50.000000    35.000000     139.000000

### Products

In [15]:
products_df = data['products.csv']
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_ID        35 non-null     int64
 1   Product_Name      35 non-null     str
 2   Product_Category  35 non-null     str
 3   Product_Cost      35 non-null     str
 4   Product_Price     35 non-null     str
dtypes: int64(1), str(4)
memory usage: 1.5 KB

In [16]:
products_df.head()

   Product_ID      Product_Name Product_Category Product_Cost Product_Price
0           1     Action Figure             Toys       $9.99        $15.99
1           2    Animal Figures             Toys       $9.99        $12.99
2           3   Barrel O' Slime     Art & Crafts       $1.99         $3.99
3           4  Chutes & Ladders            Games       $9.99        $12.99
4           5  Classic Dominoes            Games       $7.99         $9.99

In [19]:
products_df.describe()
#TODO: Change data types for price columns

       Product_ID
count   35.000000
mean    18.000000
std     10.246951
min      1.000000
25%      9.500000
50%     18.000000
75%     26.500000
max     35.000000

### Sales

In [20]:
sales_df = data['sales.csv']
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 829262 entries, 0 to 829261
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Sale_ID     829262 non-null  int64
 1   Date        829262 non-null  str
 2   Store_ID    829262 non-null  int64
 3   Product_ID  829262 non-null  int64
 4   Units       829262 non-null  int64
dtypes: int64(4), str(1)
memory usage: 31.6 MB

In [21]:
sales_df.head()

   Sale_ID        Date  Store_ID  Product_ID  Units
0        1  2022-01-01        24           4      1
1        2  2022-01-01        28           1      1
2        3  2022-01-01         6           8      1
3        4  2022-01-01        48           7      1
4        5  2022-01-01        44          18      1

In [23]:
sales_df.describe()

             Sale_ID       Store_ID     Product_ID          Units
count  829262.000000  829262.000000  829262.000000  829262.000000
mean   414631.500000      25.277034      15.014149       1.315103
std    239387.463802      14.352573       9.869417       0.830701
min         1.000000       1.000000       1.000000       1.000000
25%    207316.250000      13.000000       6.000000       1.000000
50%    414631.500000      26.000000      14.000000       1.000000
75%    621946.750000      38.000000      24.000000       1.000000
max    829262.000000      50.000000      35.000000      30.000000

### Stores

In [34]:
stores_df = data['stores.csv']
stores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Store_ID         51 non-null     int64
 1   Store_Name       51 non-null     str
 2   Store_City       51 non-null     str
 3   Store_Location   51 non-null     str
 4   Store_Open_Date  51 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.1 KB

In [37]:
stores_df.head()

,Store_ID,Store_Name,Store_City,Store_Location,Store_Open_Date
0,1,Maven Toys Guadalajara 1,Guadalajara,Residential,1992-09-18
1,1,Maven Toys Guadalajara 1,Guadalajara,Residential,1992-09-18
2,2,Maven Toys Monterrey 1,Monterrey,Residential,1995-04-27
3,3,Maven Toys Guadalajara 2,Guadalajara,Commercial,1999-12-27
4,4,Maven Toys Saltillo 1,Saltillo,Downtown,2000-01-01

# ER Diagram
---
<img src="../../ER Diagram.svg" alt="ER Diagram" width="600"/>